import "./globals.scss";
import "./layout.style.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./shared/components/UI/header/Header";
import Footer from "./shared/components/UI/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout-wrapper">
          <div>
            <Header></Header>
            <div>{children}</div>
          </div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
